config/routes.rb
Rails.application.routes.draw do
  get 'ratings/create'
  get 'ratings/destroy'
  get 'home/index'
  resources :articles
  root 'users#new'
  get 'sessions/login', to: 'sessions#login', as: :new_session
  post 'sessions/login', to: 'sessions#check'
  delete 'sessions/logout', to: 'sessions#destroy', as: :destroy_session
  resources :users, only:[:new, :create, :show]

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true
  validates :text, presence: true
  #belongs_to :user
  has_one_attached :image
  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
end

app/models/rating.rb
class Rating < ApplicationRecord
  validates :user_id, uniqueness: { scope: :article_id }
  belongs_to :user
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  validates :username, presence: true, uniqueness: true
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def current_user
    if session[:auth]
      @current_user = User.find(session[:auth]['id'])
    else
      redirect_to new_user_path
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include ArticlesHelper
  before_action :set_article,  only: [:show, :edit, :update, :destroy]
  before_action :current_user
  def index
    @articles = Article.all.ordered_by_most_recent
  end

  def show
  end

  def edit
  end

  def update
    @article.update(article_params)
    redirect_to articles_path
  end
  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to articles_path
    else
      render 'new'
    end
  end

  def destroy
    Article.find(params[:id]).destroy
    redirect_to articles_path
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  def create
    @number_of_rating = []
    @rating = current_user.ratings.new(article_id: params[:article_id])
    
  end
  def all
    @all_ratings = create.count
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def login
    @user = User.new
  end

  def check
    @current_user = User.where(username: user_params['username']).first
    if @current_user
      flash.notice = 'logged in'
      session[:auth] = @current_user
      redirect_to new_article_path
    else
      flash.notice = 'Incorrect username'
      redirect_to new_session_path
    end
  end

  def destroy
    session.destroy
    redirect_to new_user_path
    flash.notice = 'logged out'
  end

  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :current_user, except: %i[new create]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash.notice = 'User created'
      session[:auth] = @user
      redirect_to new_article_path
    else
      flash.notice = 'User not created'
      render 'new'
    end
  end
  private

  def user_params
    params.require(:user).permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
  def article_params
    params.require(:article).permit(:title, :body, :image)
  end
  def set_article
    @article = Article.find(params[:id])
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/edit.html.erb
<%= form_for @article do |a| %>
  <%= a.text_field :title, placeholder:"title"%><br>
  <%= a.text_area :body, placeholder:"body"%><br>

  <%= a.submit %>
<% end %>
<%= link_to  "Back to the list", articles_path %>

app/views/articles/index.html.erb
<div class="container">
  <div class="row">

    <div class="col s12 m7">
      <% @articles.each do |article| %>
      <div class="card small">
        <div class="card-image">
          <%= image_tag(article.image) %>
          <span class="card-title"><%= article.title.capitalize %></span>
        </div>
        <div class="card-content">
          <p>I am a very simple card. I am good at containing small bits of information.
            I am convenient because I require little markup to use effectively.</p>
        </div>
        <div class="card-action">
          <a href="#">This is a link</a>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

<table class="striped centered responsive-table">
      <thead>
      <tr>
        <th>

          <%= link_to "Add", new_article_path, class:"btn-floating btn-large waves-effect waves-light btn" %>

        </th>

      </tr>
      </thead>
      <tbody>
      <% @articles.each do |article| %>
        <tr>
          <td>
            <div class="row">

              <div class="col s12 m12 l3"><h6></div>
              <div class="col s12 m12 l3">
                <%= link_to "Read it", article_path(article), class:"waves-effect waves-light btn"%>
                <%= link_to "Delete", article_path(article), method: :delete, class:"waves-effect waves-light btn red" %>
              </div>
            </div>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>

  </div>

</div>

app/views/articles/new.html.erb
<div class="container">
  <div class="row">


    <%= form_for @article do |a| %>
      <%if @article.errors[:title][0] == "can't be blank"%>
        <p class="red-text text-darken-2"><%=flash[:notice] = "Title can't be black"%></p>
      <%end%>
      <%= a.text_field :title, placeholder:"title"%><br>
      <%if @article.errors[:body][0] == "can't be blank"%>
        <p class="red-text text-darken-2"><%=flash[:notice] = "Body can't be black"%></p>
      <%end%>
      <%= a.text_area :body, placeholder:"body", class:"materialize-textarea"%><br>
      <%= a.file_field :image, placeholder:"Add an image", class:""%>
      <div class="row">
        <div class="col s12 m12 l6">
          <%= a.submit class:"waves-effect waves-light btn" %>

        </div>
        <div class="col s12 m12 l6">
          <%= link_to  "Back to the list", articles_path %>
        </div>
      </div>

    <% end %><br>
  </div>
</div>

app/views/articles/show.html.erb
<div class="container">
  <%= link_to "Back to articles",  articles_path %>
  <%= link_to  "Edit", edit_article_path %>
  <div class="row">
    <h2><%= @article.title %></h2>
    <%= image_tag(@article.image) %>
    <p class="flow-text article-body"><%= @article.body %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyArticleApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= yield %>
    
  </body>
</html>

app/views/ratings/create.html.erb
<h1>Ratings#create</h1>
<p>Find me in app/views/ratings/create.html.erb</p>

app/views/ratings/destroy.html.erb
<h1>Ratings#destroy</h1>
<p>Find me in app/views/ratings/destroy.html.erb</p>

app/views/users/new.html.erb
<% if @user.errors.any? %>
  <div>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<h3><%= @user.username%></h3>
<%= form_for @user do |p| %>
  <%= p.label :Username %><br><br>
  <%= p.text_field :username, placeholder:"Enter a username"%><br><br>
  <%= p.submit class:'waves-effect waves-light btn'%>
<% end %>